language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly
notifications:
  email: false
before_install:
  # - sudo apt-get -qq update
  - sudo apt-get install git
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("BayesNets"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("BayesNets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
